CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS crm_db;

GRANT ALL PRIVILEGES ON auth_db.* TO 'propflow'@'%';
GRANT ALL PRIVILEGES ON crm_db.* TO 'propflow'@'%';

FLUSH PRIVILEGES;